import string

template = string.Template("""
[DEFAULTS]
cassandra_server_list=$__contrail_cassandra_server_list__
listen_ip_addr=$__contrail_listen_ip_addr__
listen_port=$__contrail_listen_port__
log_file=$__contrail_log_file__
log_local=1
log_level=SYS_NOTICE
disc_server_ip=$__contrail_disc_server_ip__
disc_server_port=$__contrail_disc_server_port__
zk_server_ip=$__contrail_zookeeper_server_ip__
rabbit_server=$__rabbit_server_ip__
list_optimization_enabled=True
$__contrail_cloud_admin_role__
$__contrail_aaa_mode__
$__contrail_ifmap_server_conf__

$__contrail_ifmap_cert__

$__contrail_ifmap_embedded_server_conf__
""")
